// user reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';

//data reducer types
export const SET_POSTS = 'SET_POSTS'
export const SET_SCHEMES = 'SET_SCHEMES'
export const SET_POST = 'SET_POST'
export const UPVOTE_POST  = 'UPVOTE_POST'
export const UNUPVOTE_POST = 'UNUPVOTE_POST'
export const DOWNVOTE_POST = 'DOWNVOTE_POST'
export const UNDOWNVOTE_POST = 'UNDOWNVOTE_POST'
export const DELETE_POST = 'DELETE_POST'
export const CREATE_POST = 'CREATE_POST'
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT'
export const UPVOTE_COMMENT  = 'UPVOTE_COMMENT'
export const UNUPVOTE_COMMENT = 'UNUPVOTE_COMMENT'
export const DOWNVOTE_COMMENT = 'DOWNVOTE_COMMENT'
export const UNDOWNVOTE_COMMENT = 'UNDOWNVOTE_COMMENT'

//ui reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA'
